### ISSUE TITLE
lengths

### ISSUE THREAD

**Issue by lxq666666** [thuiar/Self-MM#30]

**Comment by lxq666666** [comment]
Traceback (most recent call last):
  File "run.py", line 245, in <module>
    run_normal(args)
  File "run.py", line 180, in run_normal
    df = pd.DataFrame(columns=["Model"] + criterions)
  File "/home/wsw/miniconda3/envs/self_mm/lib/python3.7/site-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/wsw/miniconda3/envs/self_mm/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 242, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/home/wsw/miniconda3/envs/self_mm/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1221, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
这又怎么办
